apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: input-app-ingress
  namespace: defense
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: input-app
                port:
                  number: 8080
